### ISSUE TITLE
License and future plans?

### ISSUE THREAD

**Issue by tylru** [SungJJinKang/UE4_Interactive_Wind_and_Vegetation_in_God_of_War#1]
This is a fantastic implementation, congratulations!

Are you planning to release this under a certain license? Also, I wondered whether it would be possible to use a similar system for a global wind system, rather than just around the player, it would instead be a fixed grid in the world. Allowing wind values to be unique as you move around, this would be very useful for my current project.

Many thanks,

**Comment by SungJJinKang** [comment]
Thanks!

I added license. you can use this library freely. And I'll make document for people who use this library.

You can use this library for global wind system. But there can be performance problem if Texture size of wind map is large.
If you use small size wind map texture for large area, it may cause precision problem.

You can choose texture size, area scale ( world space ), location of wind map.
If you need wind system for large area ( area scale ), you should use large size render target.

**Comment by tylru** [comment]
Thank you so much! Indeed, there will be a balance between render target size and precision, but it is something I am happy to experiment with.
